[package]
name = "compile"
version = "0.1.0"
edition = "2024"

[dependencies]
num = "0.4.3"
utils = { version = "0.1.0", path = "../utils" }

[build-dependencies]
utils = { version = "0.1.0", path = "../utils" }
